### ISSUE TITLE
[Feature Request] Custom background color

### ISSUE THREAD

**Issue by happysurf** [sienori/simple-translate#10]
Will be great have the option for select a custom color for translation panel.
Then is perfect. :-)

**Comment by fernandosantucci** [comment]
Please keep respecting the browser theme and the desktop environment theme of operating system.

**Comment by happysurf** [comment]
> Please keep respecting the browser theme and the desktop environment theme of operating system.

Sorry but this is a no sense answer, many extensions provide color customization in various ways.
What is the problem?

**Comment by sienori** [comment]
I added background color option because there was an opinion that the panel is hard to see.
https://github.com/sienori/simple-translate/commit/5467ee359698be9c5f7a5f8d05edc75531e88b76
