### ISSUE TITLE
iframe should had a switch to disable

### ISSUE THREAD

**Issue by canufarm** [sienori/simple-translate#101]
Hi, since the update with also working in iframes now simple-translate puts html-code into text-editing fields in CMS-systems like Wordpress. So it should be possible to disable this feature, because otherwise all edited entries get the simple-translate-code without noticing it.

**Comment by sienori** [comment]
I fixed this problem. 23408bc
If this problem is completely solved, I think that the option to invalidate in iframe is unnecessary.
