### ISSUE TITLE
[Feature Request] Add option 'Don't dislpay translation button/panel for input fields'

### ISSUE THREAD

**Issue by ris58h** [sienori/simple-translate#106]
I have `Display translation panel` checked. When I select a text in an input/textarea (usually to delete or edit it) a translation panel appears.

**Comment by sienori** [comment]
I added the option `Disable translation in text field` in version2.2.0.
![option](https://user-images.githubusercontent.com/29514424/67160023-234e9d80-f387-11e9-9e83-d801637017b2.png)
Thanks!
