### ISSUE TITLE
Do not work completely

### ISSUE THREAD

**Issue by setter2002** [sienori/simple-translate#107]
I use it with Firefox 61.0.1 on Ubuntu 18.04, but simple-translate not translate all.
Any changes on google api?
I am very sad without simple translate...

**Comment by happysurf** [comment]
I confirm the problem on Firefox 62beta 11.

**Comment by sienori** [comment]
To reduce access to the API, I added an option to specify the waiting time for translation. https://github.com/sienori/simple-translate/commit/bb6bf77df7cfaa7d338e4bd86884bdfb1eef92c2
This setting does not completely suppress the error, but I think it is effective.
![waittime](https://user-images.githubusercontent.com/29514424/43473858-2860d474-952c-11e8-8382-7cf5f03f6d48.PNG)
