### ISSUE TITLE
v1.8.0 breaks grabbing text from many websites

### ISSUE THREAD

**Issue by gashtal** [sienori/simple-translate#111]
Starting from v1.8.0 up until the latest v1.9.0, when some text is highlighted from many webpages and Simple Translate's icon is clicked in the toolbar, the highlighted text is NOT automatically grabbed and translated by the addon. This is reliably reproducible when I try to translate non-English emails I receive in my Yahoo mail. Instead of the highlighted text, the word "null" is entered into the translation field in this case. Also trying to translate the non-English comments on Simple Translate's page in firefox addons portal as a test, neither any text is entered into the translation field nor is anything translated. This problem did NOT exist in v1.7.3 and the versions before that. I have been forced to keep the addon on v1.7.3 and turn off automatic updates so that I can use it.

**Comment by PolarGoose** [comment]
Very similar problem with PDF files:

Reproduction scenario:
1. Open any PDF document using Firefox
2. Highlight any word or phrase -> right click -> "Translate selected text"
3. Nothing happens

System details:
- Firefox version is 62.0
- Simple Translate Version 1.9.0

**Comment by periannath** [comment]
Disabling **"Do not display the button if translation is not required"** will solve this issue.
 
Whenever you select a text, addon sends a request for google translator API to specify language of selected text.

If you select text multiple times in short duration, google translator API blocks addon temporary because it sends too many requests in a short time.

**Comment by PolarGoose** [comment]
@periannath, I have disabled "Do not display the button if translation is not required" in the addon's settings. Nothing has changed, still have the same problem I have described above.

**Comment by periannath** [comment]
@PolarGoose Please wait for a while after changing the options to get the add-on to work properly.

After a couple of hours, the add-on worked correctly for me.

**Comment by gashtal** [comment]
I tried the "Do not display the button if translation is not required" option but that did not solve the problem and had to go back to v1.7.3 again. The problem here is that the addon fails to grab the highlighted text, rather than failing to translate it.

**Comment by gashtal** [comment]
Any comments from the developer on this issue?

**Comment by gashtal** [comment]
This problem does not seem to happen in the latest version of the add-on, so I will close the issue.
