### ISSUE TITLE
"Do not display the button if translation is not required" option breaks simple-translate

### ISSUE THREAD

**Issue by periannath** [sienori/simple-translate#112]
When I turn on the **"Do not display the button if translation is not required"** option, addon works only a few times, after that the button does not apper for selected text.

Searching from toolbar only shows **"google translate Service usage limit reached"** message.

I analyzed the source code and looked for the cause.

Whenever I select some text, addon sends a request for google translator API to specify the language of the selected text.

If I select text multiple times in short duration, google translator API blocks addon temporary because it sends too many requests in a short time.

Disabling "Do not display the button if translation is not required" makes addon translate correctly for me.

**Comment by sienori** [comment]
The behavior is by design.
When this option is enabled, you need to use the translation API to obtain the language of the selected text.
I may add this description to the option's caption in the future.

**Comment by sienori** [comment]
I improved the behavior of "Do not display the button if translation is not required" option. https://github.com/sienori/simple-translate/commit/f1d31879322a00ae06bc9a1683a42028a2afabab
This improvement will reduce access to the translation API.
