### ISSUE TITLE
Simple translate doesn't work anymore...

### ISSUE THREAD

**Issue by S3ndG** [sienori/simple-translate#115]
Hi,
today I simply selected some text from a website in english to translate it in french but it didn't work ; look to that screenshot : https://screenshots.firefox.com/fm2FkkQh34kR8IH3/support.microsoft.com
When I choose to translate the selected text with a right click, a empty small white panel appears at  the top left of the window of Firefox,  and that's all.
Are uou aware of that bug?
Thank you :)

**Comment by S3ndG** [comment]
Hmm that's very strange now it works well... I simply put my computer to stand-by mode and wake it up and now it works...
I do not understand. There is a strange bug...

**Comment by WPFilmmaker** [comment]
Could be maybe a time-out error due to too many requests from you to google translate servers? Sometimes I don't even get the white square...then it works again.

**Comment by PerJoakim** [comment]
> 
> 
> Hi,
> today I simply selected some text from a website in english to translate it in french but it didn't work ; look at that screenshot : https://screenshots.firefox.com/fm2FkkQh34kR8IH3/support.microsoft.com
> When I choose to translate the selected text with a right click, a empty small white panel appears at the top left of the window of Firefox, and that's all.
> Are uou aware of that bug?
> Thank you :)

Could you re-upload the screenshot, so other can see it too? Thank you.

**Comment by S3ndG** [comment]
> Could you re-upload the screenshot, so other can see it too? Thank you.

Done ! ;-)

**Comment by sienori** [comment]
An error has occurred due to a lot of access to the translation API.
I fixed to display errors in version 1.9.1.

![error](https://user-images.githubusercontent.com/29514424/48556498-73c3ac80-e927-11e8-91c3-d3088999708d.PNG)
