### ISSUE TITLE
Second language Error not working

### ISSUE THREAD

**Issue by on1no** [sienori/simple-translate#119]
Hi
And Sorry For My Bad English

My Target language is Arabic And its Working When i highlights any English word or sentence

But Second language isn't working
I Set My Second language to English And Checked the Automatically switch to the second language 

And When i highlighted any Arabic word or sentence it does not translate into English but translates it into the same Arabic language

So i I did the opposite i changed The Target language to English And The Second language to Arabic .
And the Same Issue 
The Target language Working 
The Second language isn't working
See the Youtube Video It will explain everything
https://youtu.be/Smc7F57mN_I

**Comment by NgYueHong** [comment]
Me too experiencing the same issue. Honestly, I never see second language working. Hope there is a fix for it soon.

**Comment by oguzzakin** [comment]
Yeah, it works with the window on toolbar but not works with selected text button. It needs to have this feature too.

**Comment by oguzzakin** [comment]
> 
> 
> Yeah, it works with the window on toolbar but not works with selected text button. It needs to have this feature too.

I see this feature has added in latest update. Thanks!

**Comment by sienori** [comment]
I added the option to switch second language on web page in version 2.0.0. Thanks.
