### ISSUE TITLE
Can you add a Option for asking to Translate

### ISSUE THREAD

**Issue by cenapatop** [sienori/simple-translate#122]
I don't want that this add on translate automaticly my selection.

Because this is a security issue. Everytime I select something it goes immediatly to google.

I would like that it popub a question where I click "ok" and then it will translate the Text

**Comment by sienori** [comment]
Please disable the option "Do not display the button if translation is not required".
If this option is disabled, the selected text will not be sent to google until you click the translate button.

**Comment by sKopheK** [comment]
hi, s3 translate firefox addon, may it rest in peace, has this nice option to translate only when some modifier key is pressed, alt key e.g. that prevented automatic translation of selected text and also made the translator more user friendly as you didnt need to click twice (select and then click the flying button) to get the translatio. would it be possible to add this option?

**Comment by Alhaitham** [comment]
@sKopheK

+1

**Comment by sienori** [comment]
I also added the ability to disable translation on the page.

1. Add `*` to URL List
→ Translation is disabled on all pages
![wildcard](https://user-images.githubusercontent.com/29514424/57133792-e4c82500-6dde-11e9-9ff0-efa1d4ecda51.PNG)

2. To use translation, click the button to enable translation
![disable](https://user-images.githubusercontent.com/29514424/57133675-856a1500-6dde-11e9-8a1e-66703db62f15.png)
