### ISSUE TITLE
It is impossible to translate any pages on the https://forums.geforce.com

### ISSUE THREAD

**Issue by oldman777** [sienori/simple-translate#127]
Page for example: 
https://forums.geforce.com/default/topic/1098097/geforce-drivers/official-418-91-game-ready-whql-display-driver-feedback-thread-released-2-13-19-/1/

**Comment by sienori** [comment]
It works in my environment. Disable the other add-ons and check the settings.

**Comment by oldman777** [comment]
Disable the other add-ons and all settings by default:
![2019-05-03_140629](https://user-images.githubusercontent.com/28647829/57133864-df51e700-6dac-11e9-8921-e53f97399cd6.jpg)

And after that, constantly recurring page:
![2019-05-03_141147](https://user-images.githubusercontent.com/28647829/57134033-6e5eff00-6dad-11e9-83f7-0951adfb9bbe.jpg)

**Comment by sienori** [comment]
Please delete the cache related to Google Translate.
![cookie](https://user-images.githubusercontent.com/29514424/57134832-53f34880-6de2-11e9-9079-3983d8c5ac3a.PNG)

**Comment by oldman777** [comment]
Just delete the cache related to Google Translate. The same issue:
![2019-05-03_154610](https://user-images.githubusercontent.com/28647829/57138381-378fe580-6dbb-11e9-8b11-5d814e5fcfcb.jpg)

**Comment by sienori** [comment]
Is it not available by clicking "I'm not a robot"?

**Comment by oldman777** [comment]
Yes, I clicking "I'm not a robot", and then appears "Invalid redirect page":
![2019-05-03_163321](https://user-images.githubusercontent.com/28647829/57140776-4083b580-6dc1-11e9-9705-c1e9ec9ac789.jpg)

**Comment by sienori** [comment]
Are you using a proxy or VPN to connect to the network?

**Comment by oldman777** [comment]
No proxy or VPN. 
<a href="https://www.speedtest.net/result/8231561524"><img src="https://www.speedtest.net/result/8231561524.png"/></a>

**Comment by sienori** [comment]
Please translate the page with Google Translate.
https://translate.google.com/

Does that problem occur?

**Comment by oldman777** [comment]
![2019-05-03_173809](https://user-images.githubusercontent.com/28647829/57144724-5a75c600-6dca-11e9-8fd1-6abcaa0fb646.jpg)
And empty page after translate
![2019-05-03_173840](https://user-images.githubusercontent.com/28647829/57144772-79745800-6dca-11e9-9a6b-813f5edcce1b.jpg)

**Comment by sienori** [comment]
Please open Google Translate in a private window.

In my environment, a 400 error occurred, but it worked for private windows.
![1](https://user-images.githubusercontent.com/29514424/57146322-0554a700-6e00-11e9-9251-eca75c53a824.png)
![2](https://user-images.githubusercontent.com/29514424/57146325-084f9780-6e00-11e9-8195-068278f30ec8.png)

In private window:
![3](https://user-images.githubusercontent.com/29514424/57146437-42b93480-6e00-11e9-8570-6cae13b8140a.PNG)

**Comment by oldman777** [comment]
In private window the same:
![2019-05-03_185258](https://user-images.githubusercontent.com/28647829/57149634-db39bf80-6dd4-11e9-8d35-0ecb0b1bf85e.jpg)
![2019-05-03_185308](https://user-images.githubusercontent.com/28647829/57149641-e0970a00-6dd4-11e9-9344-40a226593772.jpg)
![2019-05-03_185320](https://user-images.githubusercontent.com/28647829/57149653-e55bbe00-6dd4-11e9-8fa1-a80d259cb3cd.jpg)

**Comment by oldman777** [comment]
Through Japanese VPN works with no issue:
![2019-05-03_230534](https://user-images.githubusercontent.com/28647829/57163102-e1da2e00-6df8-11e9-9699-f69676b4f4d8.jpg)

Through the Swedish VPN works with no issue:
![2019-05-03_230837](https://user-images.githubusercontent.com/28647829/57163125-f1597700-6df8-11e9-94b6-b4bfd88c0196.jpg)

**Comment by sienori** [comment]
Thank you for the report!
It seems like a problem with Google translation. I can not do anything...

**Comment by oldman777** [comment]
In any case, thank you for your work.
