### ISSUE TITLE
Error: Service usage limit reached. Please wait a while and try again.

### ISSUE THREAD

**Issue by DanielRCantrell** [sienori/simple-translate#135]

**Comment by WPFilmmaker** [comment]
From simple-translate page:
"USERS: If you translate it many times in a short time, it may become unusable for a while due to the specification change of the translation API. If it occurs frequently, it is recommended to increase the translation waiting time on option page."

**Comment by sienori** [comment]
It is a limitation of Google translation API.
It will be available after 30 minutes to 1 hour.
