### ISSUE TITLE
Simple-translate does not work on vk.com

### ISSUE THREAD

**Issue by WPFilmmaker** [sienori/simple-translate#136]
Text is selected, popup appears you click on it but nothing happens.
Can anyone else reproduce this?
65.0.1 (Linux 64-bit) simple-translate v 2.0.1

**Comment by unode** [comment]
Try enabling debug mode (in settings) and you should see some messages appear in [Firefox console](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console) when you request translations.

It might tell you what's going wrong.

**Comment by WPFilmmaker** [comment]
@unode I tried to follow your suggestion but nothing is shown in the console, so I think it might be that pressing the button for translation does not work! = no request sent :/

**Comment by unode** [comment]
Do you see the console message in other websites and are you using any addon such as greasemonkey that could interfere?

Note that I don't use vk.com so I can't really tell. I tried on the homepage and it worked for me.

**Comment by sienori** [comment]
It works in my environment. Please disable other add-ons.

**Comment by WPFilmmaker** [comment]
Very weird as it seems to work intermittently. So probably a FF issue, closing.
