### ISSUE TITLE
Image links not working when Simple Translate is on

### ISSUE THREAD

**Issue by JS312RAF** [sienori/simple-translate#138]
Hello.
ST makes links on my page unclickable.
The page has no text, just images with URLs attached to them, so that might be the issue.
Everything works as it should when I disable the "simple-translate" div or the plugin itself.
**http://strouhal.art/**
Have a lovely day!
JS

**Comment by sienori** [comment]
I fixed the problem in version 2.0.2.
Thank you for the report.
