### ISSUE TITLE
Grey box at bottom of screen on Tildes.net

### ISSUE THREAD

**Issue by PopeRigby** [sienori/simple-translate#145]
[Here's](https://gitlab.com/tildes/tildes/issues/388) the [Tildes ](https://tildes.net)issue. We figured out that it must be a problem with Simple Translate

**Comment by sienori** [comment]
This problem occurs on pages where loading of inline style is blocked by Content Security Policy.
I fixed the problem in version 2.0.4. https://github.com/sienori/simple-translate/commit/9a3d07529a57ed84d87bcc1318543438b721f92f
Thanks!

**Comment by boomsya** [comment]
the same problem in 2.0.4 but i have only part ob button
https://screenshots.firefox.com/JtmTQsjBxOEhz34z/172.16.2.88

`<div style="background-image: url(&quot;moz-extension://f88fe844-6abf-4885-a008-fe21a055a157/icons/512.png&quot;); height: 22px; width: 22px; top: 10px; left: 10px;" class="simple-translate-button "></div>`

**Comment by boomsya** [comment]
on screen - local server. Page shows Nginx error (timeout)

and in google adsense administrative page - the same part of button and white box (3-4cm) under "button"

**Comment by sienori** [comment]
Does the developer tool show an error?

![dev tool](https://user-images.githubusercontent.com/29514424/54935952-b98f2200-4f64-11e9-8704-9f0de4e43f55.PNG)

**Comment by boomsya** [comment]
http://elekon.org.ua/
white screen with "button"
https://screenshots.firefox.com/KEPrjVrt319Cxhcf/elekon.org.ua

**Comment by boomsya** [comment]
https://screenshots.firefox.com/szSePfNE8yaVlSFq/www.leokon.net

http://www.leokon.net/images/cat_img/Prima/KV/KV-36-Z-P.jpg

**Comment by sienori** [comment]
There is no problem in my environment.
Are you really using version 2.0.4?
Please show me the errors on the developer tool.

![result1](https://user-images.githubusercontent.com/29514424/54984344-05d47380-4ff2-11e9-8e07-bbe0666df9f0.PNG)
![result2](https://user-images.githubusercontent.com/29514424/54984343-05d47380-4ff2-11e9-8ab7-a8f8cde08102.PNG)

**Comment by boomsya** [comment]
yes. 2.0.4
console have no errors, warnings, etc.
at now i don`t have white block 300*200

veryyy strange. And i dont restarting Firefox.

**Comment by boomsya** [comment]
oh! at now i have this bug
i just right-button clicked on link below http://elekon.org.ua and http://www.leokon.net/images/cat_img/Prima/KV/KV-36-Z-P.jpg
and select "open in new tab" and half ob button + white block showed again

**Comment by boomsya** [comment]
this problem only when open link in new tab
installed addons:
![111](https://user-images.githubusercontent.com/8008462/54988502-449d0600-4fbf-11e9-92fa-692cf984a1a9.png)

**Comment by boomsya** [comment]
![112](https://user-images.githubusercontent.com/8008462/54988588-70b88700-4fbf-11e9-8252-7072a0b2a8de.png)

**Comment by sienori** [comment]
Please disable other add-ons and try again.

**Comment by boomsya** [comment]
all others addons updated long ago
only simple-translate addon updated on this week and bug at now show in 50% of sites
last 2 udates added an error

**Comment by boomsya** [comment]
firefox 65.0.2

**Comment by sienori** [comment]
Disable add-ons means:
https://support.mozilla.org/en-US/kb/disable-or-remove-add-ons#w_how-to-disable-extensions-and-themes
![desable](https://user-images.githubusercontent.com/29514424/55000714-79887780-5016-11e9-9f4f-c1550045aba8.PNG)

**Comment by waldauf** [comment]
Hello,

I have the same problem with [Atlassians Confluence](https://cs.atlassian.com/software/confluence) platform:
![image](https://user-images.githubusercontent.com/24603883/58241039-7840a600-7d4c-11e9-82dc-5e806f1ff002.png)

Every new edit of the page create new gray box. 

Version: 2.1.0
Updated: 3. Mar, 2019

**Comment by waldauf** [comment]
Today I found out that graybox is also inputed in Google groups when I'm answering some topic.

**Comment by boomsya** [comment]
problem still exists in Joomla JCE Editor
if i have 3-4 editors on page - plugin adding some html inside every editor :(

**Comment by sienori** [comment]
I fixed the issue that code was always inserted into web pages in version 2.2.0.
The code is only inserted during translation.
Thanks!
