### ISSUE TITLE
Simple Translate Blocks Youtube embeds on Opera

### ISSUE THREAD

**Issue by gashtal** [sienori/simple-translate#147]
I recently installed this add-on on my Opera installation and it seems to be blocking embedded youtube links for some reason. I confirmed this by disabling all my add-ons on Opera and just keeping this add-on. Disabling the add-on restores youtube embedded links right away. This problem does not happen on Firefox, so it must be some kind of Opera-specific incompatibility. I am using the latest v2.0.4 and the latest stable version of Opera x64 (58.0.3135.127) on Windows 10 1809.

**Comment by sienori** [comment]
This problem has been fixed. #151
