### ISSUE TITLE
[ERROR] Error: Unknown error [No Reason Phrase]

### ISSUE THREAD

**Issue by oneturkmen** [sienori/simple-translate#148]
While trying to translate a word (or phrase), the error "Error: Unknown error [No Reason Phrase]" pops up. Is there any way to fix this?

![image](https://user-images.githubusercontent.com/17970732/55943641-a0b68a00-5c4f-11e9-8c29-feabf13b1b3b.png)

**Comment by sienori** [comment]
Please show me the debug log.
1. Enable debug mode in settings page
  ![debug mode](https://raw.githubusercontent.com/wiki/sienori/Tab-Session-Manager/img/debugMode/option.png)
2. Open developer tool on the web page
  https://developer.mozilla.org/en-US/docs/Tools#Web_Console
3. Try to translate text

Other questions:
- Which browser do you use? (Firefox or Chrome)
- Do you always get an error?

**Comment by oneturkmen** [comment]
Never mind, it got fixed somehow.

I use:

- Firefox
- No, the error had been for 1-2 hours
