### ISSUE TITLE
switch to second language not working from context menu

### ISSUE THREAD

**Issue by Gregory-K** [sienori/simple-translate#15]
![2017-11-11_202919](https://user-images.githubusercontent.com/5237731/32692409-29e47ede-c720-11e7-8634-ec141e1245e9.png)

**Comment by NgYueHong** [comment]
Yeah, this feature is awesome. It would be great if it works from context menu as well.

**Comment by sienori** [comment]
I added the option to switch second language on web page in version 2.0.0. Thanks.
