### ISSUE TITLE
错误：已达服务使用限制。请稍后再试。

### ISSUE THREAD

**Issue by ulpyuxa** [sienori/simple-translate#150]
火狐浏览器，经常出现 "错误：已达服务使用限制。请稍后再试。"，希望作者解决下。

**Comment by Ne1s07** [comment]
See #135

**Comment by ulpyuxa** [comment]
建议作者采用[#149](https://github.com/sienori/simple-translate/issues/149)此方法。

**Comment by sienori** [comment]
It is a limitation of Google translation API.
Translation will be available after 30 minutes to 1 hour.
