### ISSUE TITLE
Extension code is injected in saved local HTML files

### ISSUE THREAD

**Issue by vadim-96** [sienori/simple-translate#152]
In Firefox, when I save the html page, on each saved page I found such code like this:
`<div id="simple-translate"><div><div style="background-image: url(&quot;moz-extension://3e9baaa4-eb32-477b-a486-a3242de06839/icons/512.png&quot;); height: 22px; width: 22px; top: 10px; left: 10px;" class="simple-translate-button "></div><div class="simple-translate-panel " style="width: 300px; height: 200px; top: 0px; left: 0px; font-size: 13px; background-color: rgb(255, 255, 255);"><div class="simple-translate-result-wrapper" style="overflow: hidden;"><p class="simple-translate-result" style="color: rgb(0, 0, 0);"></p><p class="simple-translate-candidate" style="color: rgb(115, 115, 115);"></p></div></div></div></div>`
Is that ok???

**Comment by sienori** [comment]
I added the ability to disable translation on the page.
If you disable translation, HTML elements will be deleted.
![disable](https://user-images.githubusercontent.com/29514424/57131918-decf4580-6dd8-11e9-8911-b02de28f9b17.png)

**Comment by sienori** [comment]
I fixed the issue that code was always inserted into web pages in version 2.2.0.
The code is only inserted during translation.
Thanks!
