### ISSUE TITLE
Simple-translate extension and unicorn smasher extension have conflicts

### ISSUE THREAD

**Issue by ulpyuxa** [sienori/simple-translate#153]
Simple-translate extension and unicorn smasher extension have conflicts.
Enabled the simple-translate extension and open the https://www.amazon.com, and input a keyword to search. click the "unicorn smasher" extension in the search list page, the unicorn smasher extension display blank dialog. but disable Simple-translate extension, and reload the list page. and click unicorn smasher extension display normally.

**Comment by sienori** [comment]
This problem has been fixed. https://github.com/sienori/simple-translate/pull/151
