### ISSUE TITLE
V 2.1.0 adding translated text to a posting in some Forums

### ISSUE THREAD

**Issue by gekko4k** [sienori/simple-translate#158]
V 2.1.0 adding translated text when posting on certain Forums.

e.g. I check a word before posting but Simple Translate is adding that translated text at the end of the post (invisible). 
I stick with V 2.0.4 until the problem is solved.
_________________________________
Thanks for your great add-on, btw!
P.S.: Simple Translate would be absolutely perfect if you'd add (an optional) pronunciation button.
__________________________________
V 2.1.0
![V 2 1 0](https://user-images.githubusercontent.com/50341663/57255200-793abd80-7053-11e9-94ce-dded91fb408f.jpg)

V 2.0.4
![V 2 0 4](https://user-images.githubusercontent.com/50341663/57255223-85bf1600-7053-11e9-983f-39d629116536.jpg)

**Comment by sienori** [comment]
Please tell me the URL of the page where the problem occurs.

**Comment by gekko4k** [comment]
thanks for your reply.

e.g.: https://www.skyscrapercity.com

**Comment by gekko4k** [comment]
Still adding translated text in V 2.1.1.
