### ISSUE TITLE
translate button never show in reader view

### ISSUE THREAD

**Issue by sumomoneko** [sienori/simple-translate#16]
## environment 

- simple-translate 1.0.4 
  - firefox 57.0 64bit on ubuntu 16.04 
  - firefox 57.0 64bit on Windows7

## step to repro.

1.  open this URL
    http://www.boost.org/doc/libs/1_65_1/libs/iterator/doc/index.html
2. open reader view by clicking readerview icon on location bar.
3. select text

**Comment by sienori** [comment]
In Reader View, CSS and js are invalid.
Therefore, you can not use add-ons.

**Comment by def00111** [comment]
Maybe you need to wait for this bug [1]?
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1371786

**Comment by sumomoneko** [comment]
Thank for your comments.
I understand it's by firefox design.

This add-on is very useful for me even though this limitation.
ARIGATOU!  :smiley_cat:
