### ISSUE TITLE
[Question] Where translations come from

### ISSUE THREAD

**Issue by kanlukasz** [sienori/simple-translate#160]
Where the translation text comes from. Is this Google Translate or another? I can not find this information

**Comment by WPFilmmaker** [comment]
I think it comes from Google Translate.

**Comment by sienori** [comment]
Yes, it comes from Google Translate.
https://github.com/sienori/simple-translate/blob/dcce3584507b0e7e9190cc8ca856749010e87eaf/src/common/translate.js#L28-L30

**Comment by kanlukasz** [comment]
Ok, great, thank you for answer. By the way, it would be nice if you could add this info in readme file :-) . It may be important information for other people

**Comment by yuliu** [comment]
Yes, I second this.

> Ok, great, thank you for answer. By the way, it would be nice if you could add this info in readme file :-) . It may be important information for other people
