### ISSUE TITLE
Wordpress problem

### ISSUE THREAD

**Issue by agnieszkahaber** [sienori/simple-translate#162]
Hi.

This addon adds this text to every Wordpress post (with classic editor):

![Screenshot_2019-05-22 Edytuj wpis ‹ Gmina Zamość — WordPress](https://user-images.githubusercontent.com/50903074/58153849-6f7aa200-7c70-11e9-950c-068099e190f1.png)

I'm using Firefox

**Comment by Bojo78** [comment]
Hi, 
I have this problem too, but not only in Wordpress.
Тhe code below is inserted in all textboxes, creating problems with forms and emails, etc.
```html
<div id="simple-translate">
<div>
<div class="simple-translate-button isShow" style="background-image: url('moz-extension://d1244683-bb00-446f-9310-5d43fed2616b/icons/512.png'); height: 22px; width: 22px; top: 39px; left: -1px;"></div>
<div class="simple-translate-panel " style="width: 300px; height: 200px; top: 0px; left: 0px; font-size: 13px; background-color: #ffffff;">
<div class="simple-translate-result-wrapper" style="overflow: hidden;">
<p class="simple-translate-candidate" style="color: #737373;"></p>

</div>
</div>
</div>
</div>
```

**Comment by hktang** [comment]
I have the same issue too.

**Comment by fcojgodoy** [comment]
I have the same issue too. I had to remove it. I need to use WordPress and other web forms. :(

**Comment by rubcap** [comment]
Same problem here, but on Confluence Cloud wiki pages. 

Whenever I want to make an inline comment (steps: 1. select text on page 2. press "Comment" button in pop-up 3. enter comment text 4. press "Save"), the code mentioned above is inserted in the comment balloon, making it way bigger than needed to contain the comment text. This is very annoying and difficult to trace back to Simple Translate.

I added the Confluence URL to Settings >"URL list to disable translation" as a temporary work-around, but I hope you can fix this issue.

**Comment by kanlukasz** [comment]
Same problem. Its important bug!

**Comment by sienori** [comment]
I will fix this problem in the future.
Please use `Settings` > `URL list to disable translation` as a temporary workaround.

**Comment by kanlukasz** [comment]
> 
> 
> I will fix this problem in the future.
> Please use `Settings` > `URL list to disable translation` as a temporary workaround.

Is this possible to use disable URL like this - `*/wp-admin/*`
I tried but not working or i did something wrong?

I would like to exclude all Wordpress pages somehow

**Comment by Vampire** [comment]
Same happens on Google Groups, I just sent an email with a big green footer box :-(

**Comment by vivizigi** [comment]
I had this problem too. I used the Simple Translate (disabled) extension in firefox.
To fix the issue I disabled this plugin and wrote the text again and corrected them.

**Comment by sienori** [comment]
I fixed the issue that code was always inserted into web pages in version 2.2.0.
The code is only inserted during translation.

Also, I added the option to disable translation in text field.
![image](https://user-images.githubusercontent.com/29514424/67160082-023a7c80-f388-11e9-9562-cfb8699cde2c.png)

Thanks!

**Comment by kanlukasz** [comment]
> 
> 
> This seems to still happen, just with a black box instead of a green box :-(

Since this issue is closed and perhaps the repository owner has muted the thread, please create a brand new issue with step by step details. This will allow the problem to be reproduced efficiently

**Comment by Vampire** [comment]
@sienori ping
