### ISSUE TITLE
Unlock the right mouse button context menu in popup window on toolbar.

### ISSUE THREAD

**Issue by XX-J** [sienori/simple-translate#164]
I want copy, cut, past and delete text with mouse.

 Like this:

![2019 05 23-2](https://user-images.githubusercontent.com/17948007/58239666-23a02980-7d52-11e9-95ca-412d349686a2.png)

**Comment by sienori** [comment]
Copy, cut, paste and delete text with context menu works for me.

![image](https://user-images.githubusercontent.com/29514424/67160228-9ce78b00-f389-11e9-831f-77f05f538f17.png)

Firefox 69.0.3, Windows 10
