### ISSUE TITLE
Reduce permissions by replacing <all_urls>

### ISSUE THREAD

**Issue by concatime** [sienori/simple-translate#165]
Is it possible to reduce permissions of this extension?
https://github.com/itsecurityco/to-google-translate/blob/master/manifest.json#L39
https://github.com/sienori/simple-translate/blob/master/src/manifest-firefox.json#L15

**Comment by sienori** [comment]
No, it is impossible.
Simple Translate displays the translation seamlessly on the page.
For this operation, `<all_urls>` permission is required.

To Google Translate does not require permission because it simply opens the selected text on the Google Translate page.

**Comment by concatime** [comment]
Ok, I understand. Nonetheless, thank you for this extension!

**Comment by jpbruyere** [comment]
Are you absolutely sure that 'active tab' permission is not sufficient? Great addon indeed.
