### ISSUE TITLE
secondary language feature broken

### ISSUE THREAD

**Issue by Vampire** [sienori/simple-translate#175]
I have German as main language and English as secondary language configured.
This used to behave like "if anything non-german is translated it is translated to German, if anything German is translated it is translated to English".
This does not work anymore, now if you translate something German, you are just echoed back the input.

**Comment by sienori** [comment]
I fixed the problem in version 2.1.1. https://github.com/sienori/simple-translate/commit/2ea456aa824015ce52a0cae6c2eaac12dc95c12e
Thanks!
