### ISSUE TITLE
is this a privacy focused app?

### ISSUE THREAD

**Issue by wiggle-woman** [sienori/simple-translate#187]
does the app call back to google translate? which dictionary is it based on, and does usage data get sent/stored somewhere?

[proposed label: question]

**Comment by jabalv** [comment]
Yes, it from source code it looks like it's using google translate API. I see some translate history specifics, but must review code for more details.

**Comment by wiggle-woman** [comment]
does google see my ip address , user agent etc?

**Comment by jabalv** [comment]
Please refer to https://cloud.google.com/translate/data-usage
They definitely can see it, but it all depends how and if they use such information. For hiding on internet I would recommend to use VPN services.

**Comment by wiggle-woman** [comment]
thanks 

re: "..hiding on internet.." 
not hiding, just decent privacy

maybe in future add option to connect proxy between extension and google translate?

**Comment by sienori** [comment]
Simple Translate uses Google Translate API.
I would never implement a proxy function...
