### ISSUE TITLE
default target language

### ISSUE THREAD

**Issue by Vampire** [sienori/simple-translate#19]
I just installed your add-on and the default target language is `Icelandic` which happens to be the first entry in the dropdown.
Maybe it would make more sense to choose the browser UI language as default, or maybe the preferred content language as configured in Firefox if possible or at least English as fallback, and not something just very few people are actually understanding.

**Comment by sienori** [comment]
I implemented that function.
In some languages, choose the browser UI language as default, In other languages ​​choose English as default.
https://github.com/sienori/simple-translate/commit/aeb715a3561c29e5f3293b09f42ad6f15145451c
