### ISSUE TITLE
Add "match_about_blank: true" in the manifest

### ISSUE THREAD

**Issue by def00111** [sienori/simple-translate#197]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts#match_about_blank

So it works for frames, whose url is "about:blank".

**Comment by sienori** [comment]
I added `match_about_blank: true`.  https://github.com/sienori/simple-translate/commit/1410ec2dff85f346e47b6b0651c9344a08a0c28b
 Thanks!
