### ISSUE TITLE
Please don't show the 'Translate this page' item when text has been selected

### ISSUE THREAD

**Issue by FatOrangutan** [sienori/simple-translate#2]
Steps to reproduce:

1. Select some text.
2. Right click it.

Actual results: There is a submenu for Simple Translate but the only item it contains is 'Translate selected text.'

Expected results: Submenu shouldn't be used when there is only item, so the 'Translate selected text' item should directly be available in the root menu itself.

**Comment by sienori** [comment]
That problem will not be reproduced in my environment.
"Translate this page" should always be displayed in the context menu.
Please tell me your firefox version, your location, the page where the problem occurs.

**Comment by FatOrangutan** [comment]
Ah sorry, I had manually removed the 'Translate this page' item (using CSS) and completely forgot about it. Sorry for the confusion!

BTW, would you consider not showing the 'Translate this page' item when text has been selected? If user wants to translate the page, they wouldn't select some text before hand.

**Comment by sienori** [comment]
It may be implemented.
Thanks!

**Comment by sienori** [comment]
I implemented this function. https://github.com/sienori/simple-translate/commit/40eb4842e47e895dda73e7fa11e580317b16397e
