### ISSUE TITLE
target languages not sorted

### ISSUE THREAD

**Issue by Vampire** [sienori/simple-translate#20]
The entries in the target language drop down in the settings are not sorted. They are totally mixed up it seems. It would be much easier to choose a language if they were sorted properly.

**Comment by fernandosantucci** [comment]
I sorted alphabetically the list of languages after translation to Brazilian Portuguese, but Sienori is ignoring my Pull Request. The list of the original document in English continue totally disordered.

**Comment by fernandosantucci** [comment]
A definite solution would be to transform the list of languages into the "messages.json" file into an array of key/value, because in each language the order changes significantly. This would allow the array to be sorted in javascript before assembling HTML list options.

**Comment by sienori** [comment]
I implemented an alphabetical sort of the language list.
https://github.com/sienori/simple-translate/commit/f5eca930f91eae5adde7831ed5297c4bcec44ee4
