### ISSUE TITLE
Is there a limit?

### ISSUE THREAD

**Issue by gabri25ele** [sienori/simple-translate#208]
I've got
**Error: The service usage limit has been reached. Please try again in a while.**
but??? what?
Is really there a limit in the addon usage?

**Comment by sienori** [comment]
It is a limitation of Google translation API. 
It will be available after 30 minutes to 1 hour. #135

**Comment by jfbueno** [comment]
@sienori What do you think of a configuration allowing the users to use their own Google API credentials? This way, each user can have their own limit.

I'm not familiar with browser extensions but I'll be happy to try to build it if you think this will work and will fit on the scope of this extension.

**Comment by helperman** [comment]
> 
> 
> @sienori What do you think of a configuration allowing the users to use their own Google API credentials? This way, each user can have their own limit.

If you have Google API credentials you don't need this addon.
You may use Firefox's built-in translator in this way:

> browser.translation.detectLanguage=true
> browser.translation.ui.show=true
> browser.translation.engine=Google
> browser.translation.yandex.apiKeyOverride=yourGoogleApiKey

I'm not sure about other browsers though.

**Comment by jfbueno** [comment]
@helperman This feature is made to translate the whole page? If so, it does not meet my needs. I want to be able to select a few words and translate just the text that I have selected.
