### ISSUE TITLE
Doesn't translate from context menu

### ISSUE THREAD

**Issue by maxoku** [sienori/simple-translate#211]
When I try to translate a selected text with context menu item I've got an error instead of translation:
![simple](https://user-images.githubusercontent.com/17256400/79879977-b082b580-83ef-11ea-98a5-ecacb680cbea.jpg)

**Comment by sienori** [comment]
Does it work if you use the translate button or the toolbar popup instead of the context menu?

**Comment by maxoku** [comment]
It works with toolbar popup, but the button works the same like context menu.

**Comment by sienori** [comment]
It may be affected by other add-ons. Please try disabling other add-ons.

**Comment by maxoku** [comment]
Didn't work.

**Comment by sienori** [comment]
Please enable debug mode and show me the debug logs.
1. Enable debug mode in settings page
2. Press F12 on the web page to open the developer tools and look at the console tab.

**Comment by maxoku** [comment]
![debug](https://user-images.githubusercontent.com/17256400/80834243-9798b200-8bf0-11ea-8c28-31cf7f4878e7.jpg)

**Comment by sienori** [comment]
Hmm, I don't know why ...
- Does it happen on any web page? Check on github.com
- Try deleting Google Translate related cookies
  ![](https://user-images.githubusercontent.com/29514424/57134832-53f34880-6de2-11e9-9079-3983d8c5ac3a.PNG)
- Try in new profile
