### ISSUE TITLE
Don't go to new tab when opening link

### ISSUE THREAD

**Issue by rightaway** [sienori/simple-translate#212]
When you right click on a link and say Translate Selected Link it immediately switches to the newly opened tab. This isn't how the regular Open Link In New Tab right click menu option behaves.

The translation link should behave consistently and open the new tab without switching to it. It's disruptive because like when opening a regular new tab you usually want to continue reading the page you're currently on.

**Comment by sienori** [comment]
Version 2.8.0 adds the option to open page translations in the current tab! 
![image](https://user-images.githubusercontent.com/29514424/187474435-94b9f73c-5fc1-4982-84ca-175cd1e14354.png)
