### ISSUE TITLE
 sendRemoveListener on closed conduit simple-translate@sienori.549755894884

### ISSUE THREAD

**Issue by def00111** [sienori/simple-translate#213]
From this Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1633315

Maybe your add-on is broken?

I see this error alot in the console. It's get really annoying if you want to debug something in the console.

**Comment by sienori** [comment]
I think it is a bug of firefox.
The following listeners in the background script causes the error.
```
browser.storage.onChanged.addListener(() => {});
browser.contextMenus.onClicked.addListener(() => {});
```
I don't know how the developer can resolve this error.

**Comment by def00111** [comment]
[test_bug_1633365.zip](https://github.com/sienori/simple-translate/files/4567268/test_bug_1633365.zip)

Can you confirm, it will also throw the error with the test add-on i uploaded?
Just click on the icon to open the popup and then close it.

Maybe you using a listener in the content script?

**Comment by def00111** [comment]
This error seems to happen alot if you use `browser.storage.onChanged.addListener(() => {});`
in content script. If you move this to the background script then the error should go away.

**Comment by def00111** [comment]
Can you add [this](https://github.com/sienori/simple-translate/pull/312/commits/40f809ff2c5d1db4969129d12fb7a9a8e44e14d3) in your add-on code?

It fixes the errors when navigating away from a page.

**Comment by sienori** [comment]
I merged the PR. Thank you!
