### ISSUE TITLE
Button to speak the written word

### ISSUE THREAD

**Issue by procobain** [sienori/simple-translate#220]
Just as we already have a button to translate, put a button to speak the written word, I've seen it in another translator with closed code and full of advertisements, it would be nice to have this option.
Thanks for the project, hugs.

**Comment by sienori** [comment]
You can listen to the audio of the written text.
![image](https://user-images.githubusercontent.com/29514424/103687168-2e650c00-4fd3-11eb-94b2-a208c460bfa0.png)

**Comment by procobain** [comment]
Very cool, congratulations on the work.

I noticed that there was a bug, the listen button only appears with some limited number of characters, either in the original or translation. If you select a text with 199 characters, the listen button in English does not appear, and with a few more characters, the button in Portuguese did not appear here.

Thanks for the work, it's getting better.

**Comment by sienori** [comment]
The pronunciation API does not support text longer than 200 characters, so the button is not displayed.
