### ISSUE TITLE
".. selected text" doesn't work on support.mozilla.org

### ISSUE THREAD

**Issue by irvnriir** [sienori/simple-translate#223]
its 1 of sites where the context menu item doesn't work .

**Comment by hagaigold** [comment]
For me, it is not working when the first target language is the same as the selected text.
I turn on `Automatically switch to the second language`.

I enabled the debug mode and translation results are not coming back.
(the source language is recognized ok, `sourceLanguage: "en"`)

**Comment by sienori** [comment]
See: https://github.com/sienori/simple-translate/issues/96
