### ISSUE TITLE
Add the posibility to use more and better translators?

### ISSUE THREAD

**Issue by Agrotsa** [sienori/simple-translate#227]
Hi.

Your addon it the best and most handy and unintrusive. Thanks a lot for your work.

But disgracefully Google Translator is rather mediocre, some times its translations for small languages are even surrealistic with no sense at all. Could be possible to add DeepL/Linguee support?
In the actuality it supports only 11 languages, I know, but it's cosntantly growing -a year ago I think it only admitted like 5 or 6-, so I think that considering its quality and the fact that is adding new languages rapidly, Simple-translate would be very improved; after all, supporting a ton of languages but doing it as badly as Google, that many times gives incomprehensible translations, is almost like not supporting them at all. I dont know if DeepL's support for japanese, russian or chinese is very good because I cant even read those languages, but for english, spanish, german, french or portuguese is the best translator available.

Also, what about [Apertium](https://github.com/apertium)? It is as bad as Google in general, even worse for pairs of non familiar languages like english-spanish, german-arabic nad many others, but on the other hand works acceptably for pairs of languages from the same family like spanish-french, dutch-german, and so on; and besides, it is FLOSS and has support for small languages like maltese, urdu, tartar, and many others, and they are adding small american languages like quechua and guarani. I think it's a very interesting project and very useful for those speakers of languages that usually dont recieve much attention. I think is an interesting project that deserves attention.

P.S: Please consider adding Liberapay support for your donations. I don't use proprietary platforms but I'd like to thank you your work with some monetary contribution.

**Comment by sienori** [comment]
I finally implemented support for DeepL! #149 
By registering with the DeepL API, you can use DeepL with Simple Translate.  [How to register DeepL](https://github.com/sienori/simple-translate/wiki/How-to-register-DeepL-API)
![image](https://user-images.githubusercontent.com/29514424/156584969-b40c57da-0956-40a5-b125-1230242b0726.png)
