### ISSUE TITLE
Pop-up button position does not seem to be working (FF56 Ubuntu 64bit)

### ISSUE THREAD

**Issue by WPFilmmaker** [sienori/simple-translate#23]
Hi, as per title I tried to change the position where the pop-up button is supposed to appear, but I don't see any difference and the button seem to appear in random location. Am I the only one with this issue?

**Comment by arkadiusz-wieczorek** [comment]
Hi @WPFilmmaker 

in my case the pop-up window appears each other time in the same place no matter if I choose: `Top right`, `Bottom right`, `Top left` or `Bottom left` option.

FF 58.0.2, Ubuntu 16.04

**Comment by sienori** [comment]
This problem seems to be solved in the latest version.
