### ISSUE TITLE
Unable to translate words in pdf viewed with the native pdf viewer in firefox (pdf.js).

### ISSUE THREAD

**Issue by dagbdagb** [sienori/simple-translate#230]
I was hoping to use this extension together with the built-in pdf-viewer in firefox, such that I could translate unknown words in a pdf on the fly.  Sadly, this particular usecase does not appear to work. I get:

JavaScript error: moz-extension://61b39839-05f3-4a2a-9e90-71ad3c8ec823/background/background.js, line 1: Error: Could not establish connection. Receiving end does not exist.

Is this use-case technically possible to support with simple-translate?

**Comment by dagbdagb** [comment]
To clarify: 
what does not work is highlighting a word and have the translation-panel pop up on the webpage.

**Comment by aabouzaid** [comment]
I have the same issue. This option (to translate a word from a PDF file in Firefox) would be really helpful. (otherwise need to copy the word and translate it externally)

**Comment by Odnes** [comment]
This only occurs on pdfs loaded from local storage, not ones served over http. The obvious, though not always practical, workaround, is to upload them somewhere public.

**Comment by aabouzaid** [comment]
> This only occurs on pdfs loaded from local storage, not ones served over http. The obvious, though not always practical, workaround, is to upload them somewhere public.

It doesn't work with me in the both cases. (Firefox 83.0)

**Comment by Odnes** [comment]
You are correct. I was led to believe otherwise because I use another extension (Read aloud) that requires you to go through a process of "uploading to the extension", that is actually local. Not sure how it works.
In any case, by "uploading" a PDF in this way I am able to use simple-translate on it as well.

I guess there's a clue about how this feature can be implemented ;)

**Comment by sienori** [comment]
The add-on does not work on firefox's native PDF viewer.
Here is a workaround to work with PDF files you already downloaded to your system: https://support.mozilla.org/en-US/questions/1221277#answer-1126895

**Comment by ercan1104** [comment]
Simple Translate also don't translate words in Chrome (maybe the same reason), but I have caught the other error: `TypeError: Error in invocation of tabs.sendMessage(integer tabId, any message, optional object options, optional function callback): Error at parameter 'tabId': Value must be at least 0.
 `
