### ISSUE TITLE
a small issue about the french translation

### ISSUE THREAD

**Issue by S3ndG** [sienori/simple-translate#239]
Hi,
in the french version of simple translate , there is a small issue : if I click on the button in the main page of firefox, it is written 'Entrer un text".
The right sentence is "Entrer un texte"
May you fix this little thing?
Thanks!
Julien

**Comment by sienori** [comment]
I fixed it. Thank you for the report!
If you find a problem with the translation, you can fix it on [Crowdin](https://crowdin.com/project/simple-translate)!
