### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by Raayib** [sienori/simple-translate#240]
hi
in RTL languages like Arabic and Hebrew..etc, the translating content is unreadable, please can you fix it.
thank you.

https://en.wikipedia.org/wiki/Right-to-left
https://rtlcss.com/

**Comment by mx202** [comment]
Yes Yes Yes.

It's an awesome add-on BUT it really needs to support RTL languages like Arabic in the translation panel.

Thank you.

**Comment by sienori** [comment]
Thanks to yinonburgansky, it's solved!
