### ISSUE TITLE
Self-hosted all-in-one web-app and integration with extension

### ISSUE THREAD

**Issue by naDevi** [sienori/simple-translate#246]
I noticed this today however i have seen many similar extensions that does the same task (or as alternative to google translate extension). Recently evaluated this tool, then realized that's quite perfect also has advanced features to configure in settings as well. If you have free time and interest, you can work for implement below ideas to bring your project to next level

Issues: Currently this extension only support for Gtranslate (limited) and it still connect to google directly.
https://github.com/sienori/simple-translate/issues/149 https://github.com/sienori/simple-translate/issues/155 https://github.com/sienori/simple-translate/issues/227 https://github.com/sienori/simple-translate/issues/124 (related issues)

See: https://github.com/benbusby/whoogle-search (It can host on heroku, zeit, yunoapp, repl, etc and doesn't especially need a VPS. i mean about another possibility to use even without any cost)
it's almost same as google search engine and no ads, javascript, AMP links, cookies, or IP address tracking. Currently it only has one problem about image results and developer will address it within upcoming version)

Suggestions:

1. Develop a self-hosted web-app similar whoogle. 
    - It must support for multiple services similar google, bing, yandex, deepl, baidu and more by default. 
       (you may not need to use APIs for some services if develop such web app)
    - Display multiple services translate result on single page 
    - Support to add custom translate services via APIs
    - Rich input, copy, edit support or enhance to work with third-party text/document editing softwares.
    - Custom web keyboards, draw input support (similar google translate)

2. Enhance for integrate it to your existing simple translate extension (user can configure in settings and select one service for a time to use through self-hosted web-app, or they can use it as now) 

(As you able to realize, above explained idea also possible to implement **without web-app then i mean if you followed that way then this will take most from your valuable time but we'll have something nice)

**Comment by Nutr1t07** [comment]
Sorry but I can't understand how a web-app would have anything to do with a translate extension.

**Comment by naDevi** [comment]
@Nutr1t07 this doesn't has to do much special with translate extension. that is a suggestion to make this bit bigger project; not just a extension project.

So i mean about develop a self-hostable web app that can get translations from many providers (google, yandex etc) then when search eg. cat, it'll take translations (& related details) from every providers and display for result (as a list) then users don't need to check many providers, worry about other providers translation quality or keep multiple tabs on browser to compare or struggle if one provider translation wasn't good

When has self-hosted web-app then users don't connect directly to particular providers (kind of privacy friendly)

what to do with a translate extension
It can remain as now (and add option to disable current procedure and take translation from any hosted web-app for necessary users)

**Comment by IniUe** [comment]
Hi All, @naDevi @sienori @Nutr1t07 

There're self-hosted web-apps already available so you can find way to integrate with this extension

https://github.com/TheDavidDelta/lingva-translate 
demo deployment https://lingva.ml/ (self-hosted gtranslate front-end)
https://git.sr.ht/~metalune/simplytranslate_web
https://git.sr.ht/~yerinalexey/gtranslate
https://gtranslate.metalune.xyz/

**Comment by IniUe** [comment]
Sorry, it seems OP expect other platforms as all in one
