### ISSUE TITLE
Clean devtools

### ISSUE THREAD

**Issue by firefoxic** [sienori/simple-translate#248]
https://github.com/sienori/simple-translate/blob/308bac05b23f9cd5ffa336654ff71450f409e341/src/content/styles/TranslateContainer.scss#L1-L8

Please move these custom properties from `:root` to the scope they need. I am a developer, and it is very inconvenient for me to see every time, on all pages in devtools these properties, which related only to the extension.

**Comment by sienori** [comment]
I fixed it! https://github.com/sienori/simple-translate/commit/e4dcd6eb43de0522810ca3244243482fc78e5cd3
Thank you for the report!
