### ISSUE TITLE
Firefox 84.0.1 - No translation button popup and it's creating a key in local storage of websites

### ISSUE THREAD

**Issue by hushkamala** [sienori/simple-translate#249]
Hello.
Thanks for the awesome extension.

After the update of Firefox to version 84.0.1 the translation button for selected text does not pop-up.
Also it is creating local storage for almost every website with one key named "loglevel" and the value "SILENT".

**Comment by sienori** [comment]
> After the update of Firefox to version 84.0.1 the translation button for selected text does not pop-up.

It works in my environment. Try restarting the browser and reinstalling the add-on.

>  Also it is creating local storage for almost every website with one key named "loglevel" and the value "SILENT".

I fixed the problem where a key is saved to the local storage of the web page. https://github.com/sienori/simple-translate/commit/da033ef5d2220a89c2d4047c2d04cfece30a29ec
Thank you for the report!

**Comment by hushkamala** [comment]
Thanks for the fix! I'll wait for the updated build.

I did not have time to update the report but the popup button was not appearing only for the second language.
As you suggested i tried it in a clean firefox profile and it does appear for both languages. So i'm sorry for that.
