### ISSUE TITLE
Add Dark Mode support

### ISSUE THREAD

**Issue by TotalCaesar659** [sienori/simple-translate#251]
Please add Dark Mode support like in [Tab Session Manager](https://github.com/sienori/Tab-Session-Manager/pull/539#issuecomment-743733951).

**Comment by sienori** [comment]
I added the dark theme option!
![image](https://user-images.githubusercontent.com/29514424/103897336-badc0f80-5136-11eb-8406-56408b71f7bb.png)
![dark mode](https://user-images.githubusercontent.com/29514424/103897303-a9930300-5136-11eb-8a9f-13113eb4079c.png)
