### ISSUE TITLE
Unwanted additional pop-up

### ISSUE THREAD

**Issue by Odin13** [sienori/simple-translate#262]
This is a great extension--but lately it's been encumbered by an additional (blank rectangular) pop-up whose purpose seems to be to be to dismiss the original pop-up--and when used that rectangular pop-up persists! I don't see any need for this distracting new pop-up. Is there any good reason for it? Or can it be permanently disabled?

**Comment by sienori** [comment]
That problem does not occur in my environment. On which page does it occur? Please show me a screenshot.

**Comment by Odin13** [comment]
Seems this was my error. Sorry.
