### ISSUE TITLE
Error: Service usage limit reached. Please wait a while and try again.

### ISSUE THREAD

**Issue by Monessem** [sienori/simple-translate#267]
When I try to translate a lot of word the limitation msg was appear 

![image](https://user-images.githubusercontent.com/8516994/109235935-50129080-77d7-11eb-8cf0-f6d0f7327fc0.png)

**Comment by t1mron** [comment]
the same problem

**Comment by Monessem** [comment]
When trying to double-click on a phrase, after 3 phrases, an error occurred:
Error: Service usage limit reached. Please wait a while and try again.
Ext. Version 2.4.0
browser Firefox 86 win 10 x64 

> 
> 
> When I try to translate a lot of word the limitation msg was appear
> 
> ![image](https://user-images.githubusercontent.com/8516994/109235935-50129080-77d7-11eb-8cf0-f6d0f7327fc0.png)

**Comment by Fruity-0** [comment]
this is a Google ban bug that has nothing to do with the Simple translate plugin. Change ip through the tunnel, for example by the TunelBear program, and it will run for the next several dozen words.

**Comment by Monessem** [comment]
> 
> 
> this is a Google ban bug that has nothing to do with the Simple translate plugin. Change ip through the tunnel, for example by the TunelBear program, and it will run for the next several dozen words.

Other services use Google Translate work perfectly without this bug

**Comment by Fruity-0** [comment]
> 
> Other services use Google Translate work perfectly without this bug

Perhaps it depends on the given service

**Comment by sienori** [comment]
This is due to a limitation of the Google Translate API.
The same problem occurs with a [official Google Translate extension](https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb).
After an hour or so, it will be ready to use again.

**Comment by Avinash-Bhat** [comment]
@sienori, if that happens then as a fallback, the selected text could be translated with a link opening translate.google.com in new tab or something...

Something like this:
![Screenshot_2021-04-16_00-43-16](https://user-images.githubusercontent.com/1468910/114925482-b18dcd80-9e1e-11eb-8209-495fd9f1968c.png)

**Comment by Monessem** [comment]
> 
> 
> @sienori, if that happens, then as a fallback, the selected text could be translated with a link opening translate.google.com in new tab or something...
> 
> Something like this:
> ![Screenshot_2021-04-16_00-43-16](https://user-images.githubusercontent.com/1468910/114925482-b18dcd80-9e1e-11eb-8209-495fd9f1968c.png)

good optian :)
i hope @sienori adopt it

**Comment by sienori** [comment]
@Avinash-Bhat @Monessem 
I implemented it. Thanks! https://github.com/sienori/simple-translate/commit/2bd616e8663ced267067d9681447c2f18bdaa867
![image](https://user-images.githubusercontent.com/29514424/119270276-e61f5100-bc36-11eb-9aea-8ff164b9ff30.png)
