### ISSUE TITLE
Addon does not work on a specific page

### ISSUE THREAD

**Issue by sn260591** [sienori/simple-translate#268]
https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glClear.xml

**Comment by sienori** [comment]
This problem is caused by the fact that React does not work because the contentType of this page is xml.
Since Simple Translate relies on React, it will be difficult to solve this problem.

**Comment by kanlukasz** [comment]
I can confirm that it does happen sometimes.
For example, it doesn't work with `support.mozilla.org`.
Example below:

---

![Animationnnn](https://user-images.githubusercontent.com/30685349/119449659-324fbb80-bd33-11eb-8edb-bd485053bdb7.gif)

**Comment by koijigen** [comment]
@kanlukasz
"support.mozilla.org" is a "privileged page".
All add-on is disabled on privileged page by firefox browser.
But, if you want to enable that, then you can change firefox settings in "about:config".
clear a value of "extensions.webextensions.restrictedDomains".
