### ISSUE TITLE
Firefox 87: "Error: Check network connection status."

### ISSUE THREAD

**Issue by Lunasole** [sienori/simple-translate#285]
Hi. After updating to the newest version (both browser and add-on), I'm getting this error when trying to translate selected text using context menu:

> ![1](https://user-images.githubusercontent.com/19674945/113463614-6931e100-9416-11eb-9d28-87ef734476e5.jpg)

While it still works fine if translating selected text using button on toolbar.
Also there is a screenshot of debug log, it's not much more informative.

> ![2](https://user-images.githubusercontent.com/19674945/113463709-fe34da00-9416-11eb-993d-8f7ff60353eb.jpg)

I'm supposing this may be caused by some non-standard browser settings (set through about:config), but can't find anything related for now.

**Comment by Lunasole** [comment]
I'm sorry, shortly after posting here, the problem resolved.
Digging a bit deeper showed that it was caused by built-in Firefox blocker:

> ![44444444](https://user-images.githubusercontent.com/19674945/113465526-35f64e80-9424-11eb-89d5-e4f7aaa3b9d9.jpg)

So after disabling the "Tracking Content" option, extension works fine again.
> ![2222](https://user-images.githubusercontent.com/19674945/113465503-fcbdde80-9423-11eb-8e61-29099b18824a.jpg)

**Comment by Joduai** [comment]
Had the same problem after installing this addon in fx >104. Was going to uninstall this addon but I thought its problems are related to enhanced protection.
Hopefully I found your thread and although your solution solves the problem, but I didn't want to enable tracking. One might just change blocked elements list from 2 (strict) to 1 (less restricted).

Just my 2 cents if someone gets into same problem.
