### ISSUE TITLE
Extension/addons not working In Firefox and Edge on macOS Catalina 10.15.7

### ISSUE THREAD

**Issue by hafizkurniaaji** [sienori/simple-translate#296]
Previously, if I block sentences, the Simple Translate logo will appear, now nothing appears. I don't know what actually happened to my laptop, I have tried updating my web browser, it still doesn't work too.

On macOS Catalina 10.15.7, if I click on the Simple Translate icon at toolbar in two different web browser.
- Mozilla Firefox 89.0b3 (64-bit):
<img width="180" alt="gambar" src="https://user-images.githubusercontent.com/34779993/115989276-cff68480-a5e7-11eb-92fe-1086ea86a2b8.png">

- Microsoft Edge 90.0.818.46 (64-bit):
<img width="207" alt="gambar" src="https://user-images.githubusercontent.com/34779993/115989263-c240ff00-a5e7-11eb-920b-e96a72cc390e.png">

**Comment by sienori** [comment]
Can you show me the debug log?

1. Open settings page and enable debug mode
2. Replace the URL of the settings page with the following:
`moz-extension://a051d45d-a370-4a08-b1da-73016a7804e5/options/index.html#settings`
to
`moz-extension://a051d45d-a370-4a08-b1da-73016a7804e5/popup/index.html`
3. Right-click on the page and click on `Inspect`
![image](https://user-images.githubusercontent.com/29514424/115990873-9ed67e00-a600-11eb-927b-418444f615a8.png)
4. Open the console tab to see messages
![image](https://user-images.githubusercontent.com/29514424/115990994-2de39600-a601-11eb-9acf-b5a4e6d2674f.png)

Also, uninstalling and reinstalling the extension may help.

**Comment by hafizkurniaaji** [comment]
**If I follow your instruction steps, the result :**
<img width="1440" alt="gambar" src="https://user-images.githubusercontent.com/34779993/116005840-eece3880-a632-11eb-87bd-491270a4d84e.png">

**With other steps :**
<img width="1269" alt="gambar" src="https://user-images.githubusercontent.com/34779993/116005979-8764b880-a633-11eb-8797-75065c65617c.png">
<img width="1268" alt="gambar" src="https://user-images.githubusercontent.com/34779993/116006033-ca269080-a633-11eb-988c-c3c9885b3864.png">
(In this step, I clicked 3 times on the Simple-Translate icon)



I just realized, if the language of the web browser is changed from my default setting Indonesian to English (UK), changes occur, even though the pop-up instant translation feature doesn't work.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/34779993/116006594-1d99de00-a636-11eb-8a7f-5ce97b99542c.png">

**Comment by sienori** [comment]
Thanks for the details! 
I found a problem with the Indonesian language. It will be fixed in the next update.
