### ISSUE TITLE
Use Firefox design guidelines for the font used in the translation panel

### ISSUE THREAD

**Issue by FatOrangutan** [sienori/simple-translate#3]
It would be great if you could update the font of the panel according to Firefox Photon design guidelines for fonts, [available here.](http://design.firefox.com/photon/visuals/typography.html) It currently looks a little out of place.

**Comment by sienori** [comment]
I did not know that.
I will update it.

**Comment by sienori** [comment]
Font updated.

**Comment by FatOrangutan** [comment]
Thanks!
