### ISSUE TITLE
Hooliganism in Ukrainian translation

### ISSUE THREAD

**Issue by lindevel** [sienori/simple-translate#309]
I do not have an account on Crowdin.com, so I will write here
The correct translation was replaced by an offensive "ru:Російська" -> "ru:Москальська" in this commit https://github.com/sienori/simple-translate/commit/7848a1d9e853a4860c43a7af3952605645f1e9e4#r49227030
I asked the author in the comments to return the right translation, but he answered a mock

**Comment by sienori** [comment]
I fixed it. Thanks!
