### ISSUE TITLE
With frequent use of the extension, an error occurs: "We have registered suspicious traffic originating from your network"

### ISSUE THREAD

**Issue by mvbureev** [sienori/simple-translate#319]
With frequent use of the extension, an error starts to appear:
`We have detected suspicious traffic originating from your network. Please try again later. Why could this happen?`
In the screenshot, it is displayed in my default language.

![image](https://user-images.githubusercontent.com/44510263/128943438-02f10ec4-ae3f-4a87-b029-76e1d81e6091.png)

After this error starts to appear, if you open the browser developer tools on the **Network** tab and translate using the extension, then in the **Network** tab you can see the full path of the request to **https://translate.googleapis.com/...**

If you select this request and follow it, then the same error will be displayed on the open page: "**We have detected suspicious traffic originating from your network...**"
And so it is, I often do translations using the extension and this error starts to occur, because a lot of requests are sent to the translator api and therefore they become suspicious according to Google.

One gets the impression that this is an unrecoverable bug. But for example, you can add api of another translator, for example from Yandex (https://yandex.com/dev/translate/), which is successfully used in other similar extensions.

**Comment by sienori** [comment]
Try deleting the cookies related to Google Translate.
![cookie](https://user-images.githubusercontent.com/29514424/57134832-53f34880-6de2-11e9-9079-3983d8c5ac3a.PNG)

**Comment by mvbureev** [comment]
> Try deleting the cookies related to Google Translate.
> ![cookie](https://user-images.githubusercontent.com/29514424/57134832-53f34880-6de2-11e9-9079-3983d8c5ac3a.PNG)

Cleaning up Google translate cookies did not produce any results.

![2021-08-14_13-14-40 (2)](https://user-images.githubusercontent.com/44510263/129441590-c37fadc5-4b6d-436b-ac6f-43d4d1b430f3.png)
![2021-08-14_13-14-18](https://user-images.githubusercontent.com/44510263/129441601-7405b36a-c44d-434f-a896-26ed36506c1e.png)

I tried using the extension in incognito mode to eliminate the cookie effect, but it also didn't work.
Still, it seems to me that the api for translation detects suspicious activity through the ip.

![2021-08-14_13-25-14](https://user-images.githubusercontent.com/44510263/129441577-4c365909-c245-473a-bdfa-c6ea925685db.png)
