### ISSUE TITLE
Russian translation dissaper in this extentionin version 2.5.3 my firefox browser

### ISSUE THREAD

**Issue by Oleksii909** [sienori/simple-translate#323]
![зображення](https://user-images.githubusercontent.com/73876066/129487838-fab2fcaf-d3bd-462d-a203-a551a0652095.png)

**Comment by Oleksii909** [comment]
Fixed: 
![зображення](https://user-images.githubusercontent.com/73876066/129487879-0db36839-89f5-40ef-941f-e7573d0c9ca5.png)

**Comment by sienori** [comment]
This has been resolved in the current version.
