### ISSUE TITLE
Can you update the manifest.json with the Name and the Author Info please

### ISSUE THREAD

**Issue by Xanda74** [sienori/simple-translate#327]
We are scanning the manifest.json with our Snow Agents to grab info on installed Edge Plugins like name, version, author, etc 

the Version is in but there is no Author Info nor an application name 
"name": "__MSG_extName__", does not really give any value

can you please update this - we cannot use it without that that info

rgds
Alex

**Comment by sienori** [comment]
This is for localization purposes, and refers to `messages.json`.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization#internationalizing_manifest.json
https://github.com/sienori/simple-translate/blob/2fbe1849565ed5c7451358bb1141bbb7b74fb8ed/src/_locales/en/messages.json#L2-L4

In addition, the author field is not required.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/author

Are you a developer of scanning software? You may want to change the specification, as this problem can occur with other extensions.
