### ISSUE TITLE
Not working with PDF

### ISSUE THREAD

**Issue by Darikzen** [sienori/simple-translate#337]
Ad-don doesn't work with PDF at all. The button is shown and clickable, however, neither popup appears nor upper-bar panel works. 

browser: Firefox Developer Edition 94.0b4 (64-bit)

**Comment by sienori** [comment]
The add-on does not work on firefox's native PDF viewer. #230
Here is a workaround to work with PDF files you already downloaded to your system: https://support.mozilla.org/en-US/questions/1221277#answer-1126895
