### ISSUE TITLE
follow gTranslave addon behaviour

### ISSUE THREAD

**Issue by 5x3** [sienori/simple-translate#339]
can you please re-create gTranslate addon for FireFox
this is my copy installed from from mozilla website some years ago
md5: dd83ad5a53de99f3179ad879cecae5ec  gtranslate-0.14.0-an+fx.xpi

https://www.download82.com/get/download/windows/gtranslate/
or to file
http://fs2.download82.com/software/bbd8ff9dba17080c0c121804efbd61d5/gtranslate/gtranslate-0.14.0-an+fx.xpi
same md5 - so it was not modified here.

I very much like the usability of this addon and conception.
I believe it will be easy to you as a creator of this addon.
You possibly can name it the same.

some additional addon info
gTranslate by Pau Tomàs, Pierre Bertet, Éric Lemoine
gtranslate is a Firefox addon that translates the selected text using Google Translate.
https://addons.mozilla.org/en-US/firefox/addon/gtranslate/

**Comment by sienori** [comment]
Let me know what kind of behavior you like and I'll consider incorporating it into Simple Translate.
