### ISSUE TITLE
Error: Service usage limit reached. Please wait a while and try again.  Open in Google Translate

### ISSUE THREAD

**Issue by bimbachi** [sienori/simple-translate#340]
Hi,
I'm having problem with Google blocking me translation via Simple-translate, saying that I reached limit, and sending me to their translate page?
any advice ?

**Comment by eexpress** [comment]
错误：已达服务使用限制。请稍后再试。

在 Google 翻译中打开

**Comment by NgYueHong** [comment]
Me too. Facing the same problem today!!

**Comment by NgYueHong** [comment]
Now, when I try again, it is OK already. It seems to be the problem is randomly occur.

**Comment by sienori** [comment]
Switching the API to DeepL solves this. https://github.com/sienori/simple-translate/issues/149
