### ISSUE TITLE
[Feature Request] Lookup count/Cache hit count

### ISSUE THREAD

**Issue by apelly** [sienori/simple-translate#350]
I happened to be flicking through your code earlier and it struck me as kind of cool that you cache the translations.

I got to thinking about the way lingq works and I thought that if you added a hit counter to the cache that showed up during translations you'd be half way to creating the same functionality.

In case you don't know, lingq is yet another over priced "learn a language" website. It works by allowing you to translate unknown words one at a time and keeps track of the ones you struggle with so that you can practice them.

**Comment by sienori** [comment]
Hmm... Language learning is outside the scope of Simple Translate. It is not "Simple".
