### ISSUE TITLE
2.7 popup button missing

### ISSUE THREAD

**Issue by ruboard** [sienori/simple-translate#368]
After update 2.7 stopped working in waterfox classic
The translation popup button does not appear.

**Comment by wvxwxvw** [comment]
Also popup stopped showing up on the official current Firefox 91 ESR.

**Comment by sienori** [comment]
Thank you for the report!
Ver 2.7.0 did not work with legacy browsers.
In ver 2.7.2, I fixed it! https://github.com/sienori/simple-translate/commit/7bc23c32ee44675d2b45bf82e63fb651e1f5a737
