### ISSUE TITLE
[Feature Request] Adding support to translate wording on PDF & EPUBReader

### ISSUE THREAD

**Issue by NgYueHong** [sienori/simple-translate#375]
When I highlight and right click the wording in PDF file or on EPUBReader, and select "Translate selected text" from the popup menu, nothing happen.

![image](https://user-images.githubusercontent.com/6602432/160289011-ac7b4612-6c0c-4201-8d72-bb21ed9f754e.png)

The Read Aloud plugin (https://addons.mozilla.org/en-US/firefox/addon/read-aloud/) is able to read the highlighted wording. Really hope able to use Simple Translate to translate wording on PDF file & EPUBReader just like Read Aloud plugin soon. Thank you.

**Comment by sienori** [comment]
It is not possible to translate on the PDF pages. This is due to limitations of webExtensions.
