### ISSUE TITLE
DeepL Pro API doesn!t work

### ISSUE THREAD

**Issue by mur3na11** [sienori/simple-translate#376]
I double checked all the settings and it still gives me this Error: Authentication of DeepL API failed. Please set the authentication key and plan correctly on the settings page.

**Comment by emes81** [comment]
I am also experiencing the same issue! Have rolled back to using Google Translate

**Comment by sienori** [comment]
It may take a few minutes for the API to become available immediately after a new registration or resetting the authentication key. After waiting a few minutes I confirmed that it works in Pro

**Comment by emes81** [comment]
Just tried again and unfortunately several hours after entering it, my Pro authentication key (which works elsewhere) still isn't working in the add-on.

**Comment by sienori** [comment]
Make sure `DeepL API plan` is set to Pro in Simple Translate.
![image](https://user-images.githubusercontent.com/29514424/163682821-3b2ae8ea-3b02-4fdb-846c-d50c8402ac27.png)

**Comment by emes81** [comment]
Yep, Pro was definitely already selected. The only other think I can think of is a limitation on DeepL's side: I am also using the key in the browser and in my translation software (MemoQ). browser+MemoQ simultaneously isn't a problem, but maybe the add-on is seen differently.

I presume most DeepL Pro users are already using the key in software. I get a lot out of your add-on so am happy to help test this if there's a potential solution.
