### ISSUE TITLE
[BUG] Firefox Overflow Menu related issues

### ISSUE THREAD

**Issue by ilyapopovs** [sienori/simple-translate#377]
Hey 👋 

When opening the extension via a shortcut, while it's hidden in Firefox's Overflow Menu, there are 2 issues:
1. Wrong spacing on the right and bottom
2. Input field doesn't get focus

The first issue doesn't seem to appear on all systems (can't reproduce it on my Windows PC).
The second issue appears if there are more than about 5 other extensions hidden in the Overflow Menu.
Both are present for a little while, just haven't got to acting on it until now 😄 

<img width="447" alt="image" src="https://user-images.githubusercontent.com/16862411/161399710-54c8ec28-2bc1-4fe4-85f0-23cace4673e7.png">

Current system:
macos 12.2.1
MPB 13" screen, 2560x1600 px; same for a 4K screen with 4K resolution
Firefox 98.0.2

I'm open to investigating and implementing the fix myself, just would like to confirm you'd be willing to accept it (given that the code quality is good) 🙂 
Also noticed there's no explicitly declared formatting guide. If you'd like, I could add a `.prettierrc` to match the existing formatting as closely as possible 👨‍🎨

**Comment by ilyapopovs** [comment]
For the reference, this is how it looks when opened via a shortcut, but not hidden in the Overflow Menu:

<img width="458" alt="image" src="https://user-images.githubusercontent.com/16862411/161399874-5a3328c8-bf9e-43fb-bb14-ceeae213a669.png">

**Comment by ilyapopovs** [comment]
@sienori So, yay or nay? 🤔

**Comment by sienori** [comment]
PR is welcome!

**Comment by ilyapopovs** [comment]
Great, will do 👍

**Comment by ilyapopovs** [comment]
Apparently, the issues primarily stem from the Overflow Menu itself:
1. It enforces the width and height of the extension's document
2. It doesn't put extension's document in focus after it's opened (could be a race condition, but a FF issue either way)

Will create a PR for fixing the width. Not much can be done about the height or the focus issue.

The `autoFocus` attribute on the textarea is probably working as intended too, judging by the behavior described below.

---

Here's how I came to the conclusion about the extension's document missing focus being the source of the problem:
1. Apply the patch from below
2. Add Simple Translate and several other extensions so that the initially reported issue is replicate-able
3. Open Simple Translate from the Overflow menu, wait 2 seconds -> input text changes to "test", but the textarea doesn't have focus
4. Open Simple translate from the Overflow menu again, but also click on an empty space (thus, focusing extension's document) and wait 2 seconds -> input text changes to "test" AND the textarea is in focus

The patch 👇 
```
Index: src/popup/components/InputArea.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/popup/components/InputArea.js b/src/popup/components/InputArea.js
--- a/src/popup/components/InputArea.js	(revision c60a83aaeadd5bf13faff10d5fa47015525d45d0)
+++ b/src/popup/components/InputArea.js	(date 1650649759778)
@@ -32,6 +32,7 @@
     return (
       <div id="inputArea">
         <textarea
+          id='inputTextarea'
           value={inputText}
           ref="textarea"
           placeholder={browser.i18n.getMessage("initialTextArea")}
Index: src/popup/components/PopupPage.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/popup/components/PopupPage.js b/src/popup/components/PopupPage.js
--- a/src/popup/components/PopupPage.js	(revision c60a83aaeadd5bf13faff10d5fa47015525d45d0)
+++ b/src/popup/components/PopupPage.js	(date 1650649759784)
@@ -80,7 +80,13 @@
       isEnabledOnPage: tabInfo.isEnabledOnPage
     });
     if (tabInfo.selectedText !== "") this.handleInputText(tabInfo.selectedText);
+
+    setTimeout(() => this.setState({inputText: 'test'}), 2000)
   };
+
+  componentDidUpdate() {
+    document.getElementById('inputTextarea').focus()
+  }
 
   handleInputText = inputText => {
     this.setState({ inputText: inputText });

```

**Comment by ilyapopovs** [comment]
Here's the PR: https://github.com/sienori/simple-translate/pull/387

**Comment by ilyapopovs** [comment]
Found those 2 bug reports on Bugzilla, but they're both pretty old, so it's hard to tell when/if the focus issue gets fixed.
https://bugzilla.mozilla.org/show_bug.cgi?id=1526709
https://bugzilla.mozilla.org/show_bug.cgi?id=1623875

**Comment by sienori** [comment]
Thanks for the PR! I have merged it!

**Comment by ilyapopovs** [comment]
Thank you! 🙌

**Comment by esatgundogdu** [comment]
Hi, has this bug been fixed? I am currently having this issue. When I open the widget via shortcut, only sometimes it gets focused.
