### ISSUE TITLE
The translate cannot close popup in stackoverflow.com

### ISSUE THREAD

**Issue by rfrkk** [sienori/simple-translate#382]
When popup is showing , hitting outside of popup cannot close it.

### **ex:**
test website: https://stackoverflow.com/questions/2649346/test-for-empty-jquery-selection-result?noredirect=1&lq=1
test movie:

https://user-images.githubusercontent.com/137764/162547983-724791a4-4f0e-445d-bc75-777e8b38aa33.mp4

**Comment by sienori** [comment]
I could not reproduce it in my environment. Make sure you are not affected by other add-ons.
