### ISSUE TITLE
Toolbar popup doesn't display in Toggle reader view (F9)

### ISSUE THREAD

**Issue by ilkis** [sienori/simple-translate#389]
Toolbar popup doesn't display in Toggle reader view (F9).

Firefox 100.0 (64-bit)
Simple Translate Version 2.7.2

![image](https://user-images.githubusercontent.com/69108004/167271428-cff2b9a1-19f4-4f3b-9955-8fdd22e5e1f1.png)
![image](https://user-images.githubusercontent.com/69108004/167271021-d2869087-05a9-4413-892d-e1468c24dd18.png)
![image](https://user-images.githubusercontent.com/69108004/167271023-9bec5219-02b0-4a7c-bfd4-12f4c61bf9c6.png)

**Comment by sienori** [comment]
It is not possible to translate on the reader view pages.
This is due to limitations of webExtensions.
