### ISSUE TITLE
The text contained in <input> and <textarea> can not be translated.

### ISSUE THREAD

**Issue by sn260591** [sienori/simple-translate#4]
Tested in Firefox 56.

**Comment by sn260591** [comment]
I found a way to fix it. In simple-translate.js it is necessary to replace
`selectionWord = String(window.getSelection());`
with
```
if (e.target.tagName == "INPUT" || e.target.tagName == "TEXTAREA") {
    selectionWord = e.target.value.substring(e.target.selectionStart, e.target.selectionEnd);
}
else {
    selectionWord = String(window.getSelection());
}
```

**Comment by sienori** [comment]
Thank you so much!
I will include it in the next update.

**Comment by sienori** [comment]
It was included in ver.1.4.0.
Thank you very much!

**Comment by sn260591** [comment]
You forgot to apply this fix for a popup window in menu.

**Comment by sienori** [comment]
Now also valid for pop-up windows.
