### ISSUE TITLE
Focus on input field in toolbar button dialog

### ISSUE THREAD

**Issue by Vampire** [sienori/simple-translate#41]
Would be nice if the focus is on the text input field if you click the toolbar button, so that you can start typing and not have to click twice before you can start typing.

**Comment by sienori** [comment]
It will not work due to a bug in Firefox.
https://translate.googleusercontent.com/translate_c?depth=1&hl=ja&prev=search&rurl=translate.google.com&sl=en&sp=nmt4&u=https://bugzilla.mozilla.org/show_bug.cgi%3Fid%3D1324255&usg=ALkJrhjPGa_VqfW1xBkbq3YsJaWO648Iag

**Comment by Vampire** [comment]
I see, but isn't there a work-around? I didn't read all comments, but it seems there exists one.

**Comment by hdd60311** [comment]
This bug is fixed in latest nightly build.

**Comment by sienori** [comment]
This issue has been solved with firefox60.

**Comment by mustofa-id** [comment]
I faced this issue with `Firefox 72.0.1 (64-bit)` on Ubuntu 18.04.
