### ISSUE TITLE
The pop-up window on the toolbar in v.2.8.0 is not smooth 

### ISSUE THREAD

**Issue by LmarLoe** [sienori/simple-translate#428]
If you invoke a window with a hotkey, it appears one size then quickly expands, creating a flickering effect. 
Below the animation in slow motion

![st](https://user-images.githubusercontent.com/27067468/194826370-809c96b2-8bab-43d1-a0e3-2d5fd03d7c4b.gif)

**Comment by sienori** [comment]
I fixed this issue. Thanks!
https://github.com/sienori/simple-translate/commit/886e5bee810cd95fe6fa10397aa35faf919a90b0
