### ISSUE TITLE
DeepL not working

### ISSUE THREAD

**Issue by tonizombie** [sienori/simple-translate#447]
When translating full page it goes to google even when deepl is selected. And when translating only parts of text it gives this error 

> Error: Authentication of DeepL API failed. Please set the authentication key and plan correctly on the settings page.

I havent changed anything about the key or plan, but when i went to deepl site i cant see my api key anymore and instead i found this https://www.deepl.com/en/chrome-extension (Tho i cant use it as i dont use chrome)

Did something change on plugins side or deepl?

**Comment by SebTM** [comment]
Hey, were you able to fix it? I encounter the same issue - newly created DeepL account and fully verified it.

**Comment by tonizombie** [comment]
> Hey, were you able to fix it? I encounter the same issue - newly created DeepL account and fully verified it.

Sadly no, reinstalled, reconfigured and still authentication error.

I suspect this is on deepL side as i can see my api key on their website anymore, when i try Sign Up again it just says 
`"Something went wrong. Please try again or contact [DeepL Support](https://support.deepl.com/hc/requests/new)."`

**Comment by SebTM** [comment]
Hmm, I have no issues with registering/logging in directly at deepL so maybe worth checking again.

**Comment by chikega** [comment]
I'm having the same issue: To be on the safe side, I changed my authentication key in my Deepl account, but the extension still defaults to Google even though Deepl translation engine is selected.

**Comment by SebTM** [comment]
![2023-02-05_11-32](https://user-images.githubusercontent.com/17243347/216814051-80d41264-1af9-4aa6-b0a5-f0940a7346ff.png)

I've looked a bit deeper into it - and it seems an issue with account creation on DeepL side. I pulled the code and ran the addon in dev-mode and was able to see requests made to DeepL which seemed fine.

How I have solved the issue? (can't verify no additional Credit Card for new account-verification)

1. Login at DeepL, recreate token
2. Set token in the addon-settings
3. Try to translate something like in the screenshot 
4. Click on Open in DeepL Translator
5. For me I now got on the DeepL page and received the first time an error-message which told me to try later and a link to click (within the message). I clicked the link on retry it suddenly worked. 

So for me it was an account issue. Retested it (uninstalled, reinstalled) latest release from addons.mozilla.org with no issues now. If you can't solve it may write to DeepL support.

**Comment by sienori** [comment]
Generally, you can use DeepL with the following steps.
https://github.com/sienori/simple-translate/wiki/How-to-register-DeepL-API
It could be DeepL account issue.

**Comment by junglized** [comment]
Not workin for me either, I've just registered and got the same error.
