### ISSUE TITLE
Error: selectionWord is undefined

### ISSUE THREAD

**Issue by def00111** [sienori/simple-translate#45]
On this page: http://urlmidi.com/test

1) Select some text/word
2) Right-click and choose "Translate selected text"

Result: It shows an error message in browser console "Error: selectionWord is undefined"

As reported by here: https://addons.mozilla.org/firefox/addon/simple-translate/reviews/1017017/

**Comment by sn260591** [comment]
I confirm. Simple Translate doesn't work in frames.

**Comment by sienori** [comment]
I improved to work within irame. https://github.com/sienori/simple-translate/commit/e4f69c11916431889c3c14bf8e9552fe7e1f70c4
