### ISSUE TITLE
Improve response speed of popping up the translation button?

### ISSUE THREAD

**Issue by hdd60311** [sienori/simple-translate#46]
I found it seems that sometimes a little bit slow to show up the translation button

**Comment by sienori** [comment]
It takes time when this option is on; "Do not display the button if translation is not required"
This is because it detects the language of the selected text.

**Comment by hdd60311** [comment]
ok, but I would prefer a faster response speed than the default, maybe add a option for this?

**Comment by sienori** [comment]
I changed the delay at button display to 0. https://github.com/sienori/simple-translate/commit/1b8f2e89de785b79377e7ad19b3e547fc76082fd
Previously I set a delay of 200 ms to prevent malfunction, but I found out that it is not necessary.
