### ISSUE TITLE
TypeError: e.terms is undefined when target laguage is not English

### ISSUE THREAD

**Issue by athanro** [sienori/simple-translate#505]
Just select text or select text and right click and click "Translate selected text" and in browser console you get
**TypeError: e.terms is undefined** in `content.js:2:172666`

All setting are default except target language was changed to other language than English, doesn't matter which.
User-Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0
No other addons.

**Comment by pouyacodes** [comment]
The same issue #506

**Comment by sienori** [comment]
This seems to have been fixed by a change in Google's API. Simple Translate also fixed with https://github.com/sienori/simple-translate/pull/507.
