### ISSUE TITLE
Settings tab opens up after FF updates

### ISSUE THREAD

**Issue by scienmind** [sienori/simple-translate#51]
Simple Translate settings page keep opening up every time the browser is updated.

While it makes some sense to pop up sort of "what's new" page when new functionality is introduced with extension upgrade, randomly opening of settings page on browser update shouldn't happen.

Simple Translate v.1.6
FF v.57.0.3->v.57.0.4->v.58.0.0->v.58.0.1

**Comment by scienmind** [comment]
The issue seem to be due to the [backgroud.js:6](https://github.com/sienori/simple-translate/blob/master/simple-translate/background.js#L6) - this condition is a bit overreaching, as stated in [MDN-runtime.onInstalled](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onInstalled):

> Fired when the extension is first installed, when the extension is updated to a new version, and when the browser is updated to a new version.

The Info page pop up should be more selective - i have a bunch of extensions, and only small part of them display info-pages on self-updates and that's for major extension upgrades only.

**Comment by goetzc** [comment]
It's currently displaying the settings page every time the browser starts, which is annoying.

**Comment by sienori** [comment]
In the past, option page was opened when addon or firefox was updated.
I fixed it to not open it when updating firefox. 738d7f0

However, when updating the add-on, the options page is opened.
This is for initialization of the setting.

**Comment by scienmind** [comment]
Fixed as of 1.8.0. Thanks!
