### ISSUE TITLE
don't show translation button in <iframe>

### ISSUE THREAD

**Issue by hdd60311** [sienori/simple-translate#52]
I tested with some sites mentioned in this [discussion](https://github.com/CanisLupus/swift-selection-search/issues/56) and all of them don't show translation button, the developer of swift-selection-search solved its no popup issue by [this](https://github.com/CanisLupus/swift-selection-search/commit/17dbe23d7fc3b4820327d6d568b07974577e4816).

**Comment by WPFilmmaker** [comment]
I encountered this issue on firefox addons site. Simple-translate doesn't show the popup when selecting sentences in the addon review part of the site.

**Comment by sienori** [comment]
I would like to fix this problem in the future.

**Comment by sienori** [comment]
> I encountered this issue on firefox addons site. Simple-translate doesn't show the popup when selecting sentences in the addon review part of the site.

This is a limitation by firefox.
Please see: [How to enable Firefox WebExtensions on Mozilla websites](https://www.ghacks.net/2017/10/27/how-to-enable-firefox-webextensions-on-mozilla-websites/)

**Comment by WPFilmmaker** [comment]
@sienori Thank you for your explaination!

**Comment by sienori** [comment]
I improved to work within irame! e4f69c1
