### ISSUE TITLE
Ver 1.7.0 switches to "Don't display button or panel" by default (Ff 56)

### ISSUE THREAD

**Issue by WPFilmmaker** [sienori/simple-translate#59]
Hi as per title I updated simple-translate and I noticed the pop-up wasn't showing anymore.

I was going to report a ticket about that when I checked the preferences and I noticed that with the new version "Don't display button or panel" was toggled by default. 

IMHO the default option should be "Display translation button" and upgrading simple-translate should not change the previous settings as it happened to me.

**Comment by sienori** [comment]
Oh... I mistook the default option.
I fixed it, and released ver1.7.1. https://github.com/sienori/simple-translate/commit/3b67c0d6dc3565db753716729fffe155f34c253a
This fix is ​​for users who have not installed ver1.7.0 yet.

**Comment by WPFilmmaker** [comment]
Thanks a lot @sienori! And thank you very much for your great work with this extension!
