### ISSUE TITLE
Move position of translation panel

### ISSUE THREAD

**Issue by antiphp** [sienori/simple-translate#60]
When reading a long (foreign) text I find it important that you don't get interrupted or disturbed. The "translation panel" supports that almost perfectly. Almost because it **overlaps the original selection**/text. So I would suggest moving the translation panel to a position where it does not.

Suggestion:
**Above** is IMHO better because it overlaps text that one usually read already.
**Below** is also okay because it's kind of where one expects that kind of translation but where it may overlap following parts of the same sentence. Maybe make it configurable?

**Comment by arkadiusz-wieczorek** [comment]
I'm totally agree :)

**Comment by sienori** [comment]
I made the translation panel draggable in version 2.2.0. https://github.com/sienori/simple-translate/pull/183

![Drag panel](https://user-images.githubusercontent.com/29514424/67160451-c9040b80-f38b-11e9-894b-b6c896424658.gif)

Thanks!
