### ISSUE TITLE
add possiblity to use Deepl

### ISSUE THREAD

**Issue by aqwserf** [sienori/simple-translate#63]
In addition to google translate, would you please thinking to add on option to use Deepl (https://www.deepl.com/translator) to you addon ?
Thanks

**Comment by sienori** [comment]
Sorry, I will not add DeepL Translator to the addon.
Because there are too few languages ​​supported.

**Comment by aqwserf** [comment]
Ok I understand ! Thanks for your quick feedback and for your addon !
