### ISSUE TITLE
the target language only has one candidate "undefined"

### ISSUE THREAD

**Issue by lqhl** [sienori/simple-translate#71]
As shown in the screenshot, the candidate list of the target language only has one candidate "undefined":
<img width="679" alt="screen shot 2018-03-06 at 6 02 42 pm" src="https://user-images.githubusercontent.com/688173/37026347-14b47804-2169-11e8-8f4e-f0119b571ad8.png">

The candidate list of language for the secondary language also gone. The candidate list was right before. I'm not sure what changed. The translation function still works though.

version:
- Simple Translate: Version. 1.7.2
- Firefox: 58.0.2 (64 bit) on macOS

**Comment by sienori** [comment]
There was a problem with the format of the zh-cn language list. https://github.com/sienori/simple-translate/commit/dacf028bb9297f4fc68e6232b2f2a692f26ddcd1
I fixed it and updated to version 1.7.3.
Thank you for your report!

**Comment by lqhl** [comment]
Thank you!
