### ISSUE TITLE
Add-on page opening every time Firefox opens

### ISSUE THREAD

**Issue by Matt17BR** [sienori/simple-translate#76]
I don't know if this is voluntary or not, but it's a bit annoying that the extension opens its settings page every time or every second time Firefox starts up/updates. Would be nice to at least have a toggle for it :/

**Comment by WPFilmmaker** [comment]
I have seen this behavior sometimes. I don't think it is intended by the developer. I think it is ether a bug, or simply a new version was updated (easy to check by looking at the version number)

**Comment by Matt17BR** [comment]
I don't think it's caused by the add-on updating. I've been checking whether the version number changed every time the window appeared and that wasn't the case.

**Comment by sienori** [comment]
In the past, option page was opened when addon or firefox was updated.
I fixed it to not open it when updating firefox. https://github.com/sienori/simple-translate/commit/738d7f0f6ac82652d55ac12bd6c9e13873e8e512

However, when updating the add-on, the options page is opened.
This is for initialization of the setting.
