### ISSUE TITLE
Request: Customize context menu items

### ISSUE THREAD

**Issue by mzso** [sienori/simple-translate#79]
Hello!

I find it rather inconvenient that I have to find the translate selected text option in a sub-menu. And it's not even the first option, but it's the translate page, which I never use. I could use the button for that. (But I also have google translate page bookmarked so I don't even use that)

If I could configure the addon to not show the translate page option in the context menu, than the desired selected text option could be top level and a lot more convenient.

**Comment by sienori** [comment]
I will implement this option in the future.
Thanks.
duplicate: #5
