### ISSUE TITLE
Do you have a Chrome version ? 

### ISSUE THREAD

**Issue by mikhoul** [sienori/simple-translate#82]
I was looking for a light translation extension with a popup and I see your webext do this but I don't see a Chrome version, could you make one ? 

Regards :octocat:

**Comment by sienori** [comment]
I may release a chrome version in the future.
Thanks.

**Comment by sienori** [comment]
I released Chrome version. Thanks!
https://chrome.google.com/webstore/detail/simple-translate/ibplnjkanclpjokhdolnendpplpjiace
