### ISSUE TITLE
Simple-Translate broken with NoScript (Incompatbility on Ubuntu 16.04)

### ISSUE THREAD

**Issue by WPFilmmaker** [sienori/simple-translate#84]
As per title, with FF 56 everything was fine, with 59 the button doesn't appear anymore (despite being toggled in the options). I tried to restart FF and simple-translate but without luck. Can someone else confirm this?

**Comment by WPFilmmaker** [comment]
Update: Simple-Translate is still dead. I checked the reviews on addons website and one user today reported that it wasn't working. He didn't specfy the OS but I am assuming it was a linux distro.. @sienori do you have a chance to test it on a linux platform?Tank you.

**Comment by sienori** [comment]
It worked normally on Devian9.x FF59.
Please delete the browser cookie.

**Comment by WPFilmmaker** [comment]
@sienori I deleted cookies and cache, restarted FF and nothing changed.

Then I dsabled all my addons and Simple-Translate worked again! I started enabling each one after another checking S-T and the culprit is Noscript!

If it is enabled the pop-up doesn't appear. I thought the issue could be that I was blocking certain script, but then I tried on a page where all the scrips were allowed and it didn't work.

So I can confirm that there is (at the least on my system Lubuntu 16.04.3, latest FF) a problem between Noscript  10.1.7.5 and Simple-Translate 1.73

No the question is what exactly Noscript does that breaks S-T :/

I tried to export Noscript settings unfortunately there is nothing useful there, just the websites and their privileges. If you can tell me how I could provide more info, I will be happy to do so.

**Comment by WPFilmmaker** [comment]
A little update, I updated FF to 60.0 and the problem persist. Unless I disable Noscropt Simple-Translate won't work. If I enable "Display the context menu"  I get the popup with three dots*. Therefore I am assuming the addon is being blocked when it tries to reach google servers by some NoScript function. @sienori Do you think you can look into this?

Noscript 10.1.8.1 and Simple-Translate 1.73, FF 60, Lubuntu 16.04.3

* http://upl.co/uploads/Screenshot-from-20180512-1129361526121350.png

**Comment by C37H40O9** [comment]
In General NoScript settings on Default tab set 'fetch' option. After that S-T works for me (Firefox 60, OpenSuse 42.3)

**Comment by WPFilmmaker** [comment]
@C37H40O9 Thank you it works!
@sienori seems that 'fetch' is about XmlHttpRequest or Fetch APIs, is it normal that S-T doesn't  work without them? Is there something that can be done apart from C37H40O9's workaround? (which however affects Noscript protection?)

**Comment by sienori** [comment]
Thanks for the report!
This add-on uses XmlHttpRequest for translation.
There is no choice but to change Noscript settings.
