### ISSUE TITLE
Add option to disable pop-up for selected text in form fields

### ISSUE THREAD

**Issue by vertigo220** [sienori/simple-translate#87]
If I'm selecting text in a form field, such as the one I'm typing in now, odds are I'm selecting something I typed, so I don't need it translated. But the pop-up comes up and gets in the way, so the option to disable it for selected text in fields would be really helpful.

**Comment by sienori** [comment]
I added the option `Disable translation in text field` in version2.2.0.
![option](https://user-images.githubusercontent.com/29514424/67160023-234e9d80-f387-11e9-9e83-d801637017b2.png)
Thanks!
