### ISSUE TITLE
Enable the translation on AMO

### ISSUE THREAD

**Issue by S3ndG** [sienori/simple-translate#96]
Hi,
I think this could be great to have Simple Translate working on AMO ( https://addons.mozilla.org )
For now, it doesn't work.
Thanks in advance.

**Comment by sienori** [comment]
It is a limitation by firefox, but a workaround exists.
(It is an informal method. I can not support it.)

https://addons.mozilla.org/ja/firefox/addon/scroll_anywhere/
> does not work HERE on https://addons.mozilla.org/ (blocked by Firefox) BUT! it can be enabled by creating new key `privacy.resistFingerprinting.block_mozAddonManager` in `about:config` page with boolean `true` value, and in the key `extensions.webextensions.restrictedDomains` remove domain `addons.mozilla.org`

**Comment by S3ndG** [comment]
OK thanks for the info!
