### ISSUE TITLE
Button/panel elements added to iframes (WYSIWYG editors issue)

### ISSUE THREAD

**Issue by jusuff** [sienori/simple-translate#97]
When Simple Translate button or panel is enabled, extension adds few html elements to IFRAMEs content.

This is an issue when using iframe-based wysiwyg editor (for example TinyMCE) - those elements are added to editor content and later saved.

Steps to reproduce:

- Visit https://www.tinymce.com/
- In the middle of screen editor example will be loaded
- In editor menu select View / Source code
- At the end of editor content source you will see Simple Translate button/panel elements

![obraz](https://user-images.githubusercontent.com/278035/40979839-42659372-68d7-11e8-88bb-58f88074f840.png)

**Comment by boomsya** [comment]
the same bug https://github.com/sienori/simple-translate/issues/100

**Comment by sienori** [comment]
Thanks for the report!
I fixed this problem. https://github.com/sienori/simple-translate/commit/23408bcd256769a709dfbd4c07a1ed38128ed6dc

**Comment by jusuff** [comment]
@sienori thanks for the fix. Looks like this issue is fixed.
