### ISSUE TITLE
Request: Port it to Chromium

### ISSUE THREAD

**Issue by mikhoul** [sienori/simple-translate#99]
I really like this addon on Firefox and  I'd like to use it too when I use Chromium for my work.

You should port it to Chromium since both Firefox and Chromium use the same technology (WebExt) now.

Thanks for your work :octocat:

**Comment by sienori** [comment]
I released Chrome version. Thanks!
https://chrome.google.com/webstore/detail/simple-translate/ibplnjkanclpjokhdolnendpplpjiace
